"use client";
import {useState} from "react";
import type {WeekResource,WeekActionRow} from "@/lib/study/workflow";
import {canOpenWeekSolutions} from "@/lib/study/course-study-flow";
import {sourceProcessingLabel} from "@/lib/study/course-binder-overview";
export function CourseMaterialList({resources,weeks}:{resources:WeekResource[];weeks:WeekActionRow[]}){
 const [search,setSearch]=useState("");const [type,setType]=useState("all");const [weekId,setWeekId]=useState("all");
 const visible=resources.filter(file=>file.title.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())&&(type==="all"||file.resource_type===type)&&(weekId==="all"||file.teaching_week_id===weekId));
 return <section><h2>Materials</h2><div className="course-material-filters"><label>Find a file<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Lecture, exercise, filename…"/></label><label>Teaching week<select value={weekId} onChange={e=>setWeekId(e.target.value)}><option value="all">All weeks</option>{weeks.map(w=><option key={w.teaching_week_id} value={w.teaching_week_id}>Week {w.week_no}</option>)}</select></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{[...new Set(resources.map(r=>r.resource_type))].map(t=><option key={t} value={t}>{t.replaceAll("_"," ")}</option>)}</select></label></div><p className="muted" role="status">{visible.length} materials</p><ul className="course-material-list">{visible.map(file=>{const week=weeks.find(w=>w.teaching_week_id===file.teaching_week_id);const locked=["solution","exam_solution"].includes(file.resource_type)&&(!week||!canOpenWeekSolutions(week));return <li key={file.id}><div><strong>{file.title}</strong><span>{file.resource_type.replaceAll("_"," ")}{week?` · Week ${week.week_no}`:""} · {sourceProcessingLabel(file.processing_status)}</span></div>{locked?<span>Record independent work to unlock</span>:file.drive_url?<a className="secondary-button" href={file.drive_url} target="_blank" rel="noreferrer">Open file ↗</a>:<span>No file link recorded</span>}</li>;})}</ul>{!resources.length?<p>Add your first lecture or exercise sheet using Add material.</p>:null}</section>;
}
