import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,open} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {startProvider,sessionFor,courseId,owner} from './isolated-study-provider.mjs';
const output=resolve(process.env.UX_EVIDENCE_DIR??'evidence/application-journey');await mkdir(output,{recursive:true});
const env={...process.env,STUDYOS_TEST_DIST:'.next-ux-test',NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:3199',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'isolated-publishable-key',APP_ORIGIN:'http://127.0.0.1:3110',STUDYOS_AI_ENABLED:'false',OPENAI_API_KEY:'',SUPABASE_SECRET_KEY:'',SUPABASE_SERVICE_ROLE_KEY:''};
const checks=[],screenshots=[],timings=[],errors=[];
const log=await open(resolve(output,'server.log'),'w');
function child(args,overrides={}){return spawn(process.execPath,args,{env:{...env,...overrides},stdio:['ignore',log.fd,log.fd],windowsHide:true});}
const provider=await startProvider();let app,mockedAiApp,browser,page;
try{
 if(process.env.UX_SKIP_BUILD!=='true'){const build=child(['node_modules/next/dist/bin/next','build']);assert.equal(await new Promise(r=>build.on('exit',r)),0,'Isolated production build failed; see server.log');}
 app=child(['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3110']);
 for(let i=0;i<150;i++){try{if((await fetch('http://127.0.0.1:3110/login')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
 const module=process.env.PLAYWRIGHT_MODULE??'playwright';const {chromium}=await import(module.startsWith('C:')?pathToFileURL(module).href:module);browser=await chromium.launch({headless:true});
 const context=await browser.newContext({reducedMotion:'reduce'});const session=sessionFor();await context.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(session)).toString('base64url'),domain:'127.0.0.1',path:'/'}]);
 page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const go=async(path,heading)=>{const start=performance.now();await page.goto('http://127.0.0.1:3110'+path);await page.getByRole('heading',{level:1,name:heading,exact:true}).waitFor();timings.push({path,kind:'cold-document',ms:Math.round(performance.now()-start)});};
 const shot=async(name)=>{await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:resolve(output,name+'.png'),fullPage:true});screenshots.push(name+'.png');};
 for(const width of [1280,320,375,390,430,768]){
  await page.setViewportSize({width,height:900});
  for(const [name,path,title] of [['today','/','Today'],['courses','/courses','Courses'],['course','/courses/'+courseId,'Differentialgleichungen'],['materials','/resources','Materials'],['assistant','/assistant','GPT-6 Luna'],['progress','/progress','Progress'],['settings','/more','Settings & tools']]){
   await go(path,title);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`${name} overflow at ${width}`);
   if(width===1280||width===390)await shot(name+'-'+width);
  }
 }
 checks.push('Actual production route compositions render at six widths without horizontal overflow');
 await page.setViewportSize({width:1280,height:900});
 for(const [label,title] of [['Today','Today'],['Courses','Courses'],['Assistant','GPT-6 Luna'],['Progress','Progress'],['Courses','Courses']]){
  await page.locator('.workspace-desktop-nav').getByRole('link',{name:label,exact:true}).hover();await page.waitForLoadState('networkidle');const start=performance.now();await page.locator('.workspace-desktop-nav').getByRole('link',{name:label,exact:true}).click();await page.getByRole('heading',{level:1,name:title,exact:true}).waitFor();timings.push({path:new URL(page.url()).pathname,kind:'warm-prefetched-navigation',ms:Math.round(performance.now()-start)});
 }
 await page.setViewportSize({width:1280,height:900});await go('/courses','Courses');await page.getByRole('searchbox').fill('absent');assert.equal(await page.locator('.directory-course').count(),0);await page.getByRole('searchbox').fill('differential');await page.getByRole('link',{name:'Open course',exact:true}).click();await page.getByRole('heading',{level:1,name:'Differentialgleichungen'}).waitFor();checks.push('Course directory search and rediscovery');
 await page.getByRole('link',{name:'Weeks',exact:true}).click();await page.waitForURL('**?tab=weeks');await page.locator('#week-1').waitFor();assert.equal(await page.getByRole('link',{name:/Official solution/}).count(),0);assert.equal(await page.getByRole('link',{name:/Week 1.*Lecture/}).count(),1);assert.equal(await page.getByRole('link',{name:/Week 1.*Exercise/}).count(),1);await shot('weeks-desktop');checks.push('Week 1 lecture and exercise discovered; solution gate remains enforced');
 await page.getByRole('link',{name:'Ask Study Assistant',exact:true}).click();assert.equal(await page.locator('#assistant-course').inputValue(),courseId);assert.equal(await page.locator('#assistant-question').isDisabled(),true);checks.push('Course context retained; paid assistant submission disabled');
 await go('/resources?course='+courseId+'#manual-registration','Differentialgleichungen · Materials');const dialog=page.getByRole('dialog');await dialog.waitFor();assert.ok(await dialog.evaluate(el=>el.contains(document.activeElement)));await page.keyboard.press('Tab');assert.ok(await dialog.evaluate(el=>el.contains(document.activeElement)));await shot('add-material-dialog');await dialog.locator('[name=title]').fill('Additional lecture.pdf');await dialog.locator('[name=driveUrl]').fill('https://drive.google.com/file/d/isolated-new-file/view');await dialog.locator('[name=courseId]').selectOption(courseId);await dialog.locator('[name=weekNo]').fill('1');provider.state.rejectWrites=true;await dialog.getByRole('button',{name:'Save material',exact:true}).click();await dialog.getByRole('alert').waitFor();assert.equal(provider.state.resources.length,3);provider.state.rejectWrites=false;await dialog.getByRole('button',{name:'Save material',exact:true}).click();await dialog.getByRole('status').filter({hasText:'Saved.'}).waitFor();assert.equal(provider.state.resources.length,4);await page.keyboard.press('Escape');await page.getByRole('heading',{name:'Additional lecture.pdf'}).waitFor();checks.push('Real material handler rejects failed writes and persists successful registration in isolated provider');
 await go('/practice?course='+courseId,'Differentialgleichungen');
 await page.getByRole('button',{name:'Start review',exact:true}).click();await page.locator('#review-working').fill('The derivative is 2x.');await page.getByRole('button',{name:'Confidence 4 of 5'}).click();await page.getByRole('button',{name:/Lock answer/}).click();await page.getByRole('button',{name:'Correct',exact:true}).click();await shot('active-study');provider.state.rejectWrites=true;const denied=page.waitForResponse(r=>r.url().endsWith('/api/study/attempt'));await page.getByRole('button',{name:'Save & next',exact:true}).click();assert.equal((await denied).status(),403);await page.locator('.review-workspace .error').waitFor();assert.equal(provider.state.attempts.length,0);provider.state.rejectWrites=false;await page.getByRole('button',{name:'Save & next',exact:true}).click();await page.getByRole('heading',{name:'1 attempts completed'}).waitFor();assert.equal(provider.state.attempts.length,1);checks.push('Real session and answer handlers persist only successful attempts; failure never shows completion');
 await go('/progress','Progress');assert.equal(await page.locator('.progress-headline-metrics strong').first().textContent(),'1');assert.equal(provider.state.attempts.length,1);checks.push('Progress renders persisted isolated learning evidence after a successful attempt');
 await go('/','Today');await page.getByRole('heading',{name:'What to study next'}).waitFor();await page.getByText('Exercise sheet 1',{exact:true}).first().waitFor();checks.push('Planner recommendation and upcoming deadline visible');
 await page.setViewportSize({width:390,height:900});await page.locator('.workspace-mobile-nav').getByRole('link',{name:'Courses',exact:true}).click();await page.getByRole('link',{name:'Open course',exact:true}).click();await page.getByRole('link',{name:'Weeks',exact:true}).click();await page.locator('#week-1').waitFor();await page.getByRole('link',{name:'Ask Study Assistant',exact:true}).click();assert.equal(await page.locator('#assistant-course').inputValue(),courseId);await page.locator('.workspace-mobile-nav').getByRole('link',{name:'More',exact:true}).click();await page.getByRole('heading',{name:'Settings & tools',level:1}).waitFor();checks.push('Mobile bottom navigation completes course, week, assistant and settings journey');
 await go('/practice?course='+courseId,'Differentialgleichungen');await page.getByRole('button',{name:'Start review',exact:true}).click();await page.locator('#review-working').fill('Recover this unfinished derivative.');await page.getByText('Unfinished work stored in this tab · not synced across devices',{exact:true}).waitFor();await page.reload();await page.getByText('Unfinished work restored from this browser tab. Continue solving before revealing the answer.',{exact:true}).waitFor();assert.equal(await page.locator('#review-working').inputValue(),'Recover this unfinished derivative.');await page.getByRole('button',{name:'Confidence 4 of 5'}).click();await page.getByRole('button',{name:/Lock answer/}).click();await page.getByRole('button',{name:'Correct',exact:true}).click();await page.route('**/api/study/attempt',route=>route.abort('internetdisconnected'));await page.getByRole('button',{name:'Save & next',exact:true}).click();await page.getByText('Queued for signed-in account sync',{exact:true}).waitFor();assert.equal(provider.state.attempts.length,1);assert.equal(await page.locator('.practice-outcome-ledger').getByText('Recorded',{exact:true}).count(),0);const pending=await page.evaluate(()=>JSON.parse(localStorage.getItem('semester-os:pending-attempts:v2')??'[]'));assert.equal(pending[0].ownerId,owner);checks.push('Refresh restores unfinished work; interrupted write remains owner-bound and queued, never Recorded');await page.unroute('**/api/study/attempt');
 await page.setViewportSize({width:1280,height:900});
 await go('/more','Settings & tools');await page.getByRole('link',{name:'Drive & Calendar connections →',exact:true}).click();await page.getByRole('heading',{name:'Connections',level:1,exact:true}).waitFor();await page.getByRole('link',{name:'Connect Drive',exact:true}).waitFor();await page.getByRole('link',{name:'Connect Calendar',exact:true}).waitFor();await shot('connections');checks.push('Actual Drive and Calendar connection controls discoverable without readiness diagnostics');
 await go('/courses/'+courseId+'#week-1','Differentialgleichungen');await page.waitForURL('**?tab=weeks#week-1');await page.locator('#week-1').waitFor();checks.push('Legacy week deep link opens the corresponding URL-backed view');
 for(const tab of ['materials','practice','progress','settings','exams']){await go('/courses/'+courseId+'?tab='+tab,'Differentialgleichungen');await shot('course-'+tab);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}
 await go('/courses/'+courseId+'?tab=progress','Differentialgleichungen');await page.getByRole('heading',{name:'Topics & learning evidence'}).waitFor();await page.goBack();await page.goForward();await page.getByRole('heading',{name:'Topics & learning evidence'}).waitFor();checks.push('Course URL tabs survive Back and Forward');
 const other=await browser.newContext();await other.addCookies([{name:'sb-127-auth-token',value:'base64-'+Buffer.from(JSON.stringify(sessionFor('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'))).toString('base64url'),domain:'127.0.0.1',path:'/'}]);const otherPage=await other.newPage();await otherPage.goto('http://127.0.0.1:3110/');await otherPage.getByRole('heading',{name:'Welcome to StudyOS'}).waitFor();assert.equal(await otherPage.getByText('Differentialgleichungen',{exact:true}).count(),0);checks.push('Second isolated account cannot see owner courses');await other.close();
 provider.reset({empty:true});await go('/','Welcome to StudyOS');await shot('onboarding');await page.getByRole('link',{name:'Create semester',exact:true}).click();await page.locator('[name=displayName]').fill('Winter semester 2026');await page.locator('[name=startsOn]').fill('2026-10-05');await page.locator('[name=endsOn]').fill('2027-03-31');await page.getByRole('button',{name:'Create semester workspace'}).click();await page.getByRole('heading',{name:'Choose your first course'}).waitFor();await page.locator('[name=displayName]').fill('Differentialgleichungen');await page.getByRole('button',{name:'Add course',exact:true}).click();await page.getByText('Course added.',{exact:false}).waitFor();assert.equal(provider.state.courses.length,1);checks.push('New user creates semester and course through real handlers and stateful test RPCs');
 const anonymous=await browser.newPage();await anonymous.goto('http://127.0.0.1:3110/courses');assert.match(anonymous.url(),/\/login/);await anonymous.close();checks.push('Unauthenticated core routes still redirect to login');
 // A second isolated runtime enables the composer with no API key. Every AI POST
 // is intercepted in Chromium; this never reaches the paid model endpoint.
 mockedAiApp=child(['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3112'],{STUDYOS_AI_ENABLED:'true',APP_ORIGIN:'http://127.0.0.1:3112'});
 for(let i=0;i<150;i++){try{if((await fetch('http://127.0.0.1:3112/login')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
 let aiPosts=0;await page.route('**/api/study/assistant',route=>{aiPosts++;return route.fulfill(aiPosts===1?{status:503,json:{ok:false,error:'Isolated assistant unavailable. Try again.'}}:{json:{ok:true,answer:'A mocked explanation: \\(x^2\\).\n```python\nx = 2\n```',context:{sources:[]}}});});
 await page.setViewportSize({width:390,height:900});await page.goto('http://127.0.0.1:3112/assistant?course='+courseId);await page.locator('#assistant-question').fill('Explain the derivative');await page.getByRole('button',{name:'Ask Luna',exact:true}).click();await page.getByRole('alert').filter({hasText:'Isolated assistant unavailable'}).waitFor();await page.getByRole('button',{name:'Retry last question'}).click();await page.locator('.assistant-assistant').waitFor();assert.equal(aiPosts,2);assert.equal(await page.locator('.assistant-assistant code').textContent(),'x = 2\n');await page.locator('.assistant-assistant math').waitFor();await shot('assistant-mocked-retry-mobile');checks.push('Actual Assistant page recovers from mocked failure and renders mathematics/code without paid requests');
 assert.deepEqual(errors,[]);
}catch(error){if(page){await page.screenshot({path:resolve(output,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(resolve(output,'failure.txt'),await page.locator('body').innerText().catch(()=>''));}throw error;}finally{
 await writeFile(resolve(output,'manifest.json'),JSON.stringify({kind:'production-application-isolated-provider',checks,screenshots,timings,errors,limitations:['Synthetic provider confirms application flow, not live Supabase RLS or Google consent','Main runtime has paid AI disabled; separate no-key runtime intercepts every Assistant POST','Cold document measurements are not warm navigation acceptance']},null,2));
 await browser?.close();app?.kill();mockedAiApp?.kill();await provider.close();await log.close();
}
console.log(JSON.stringify({checks,screenshots:screenshots.length,errors},null,2));
